extends:
  - "airbnb"
globals:
  window: true
plugins:
  - "import"
settings:
  import/resolver:
    webpack:
      config: webpack.config.js
rules:
  import/no-unresolved:
    - "error"
    - ignore:
      - "trustpilot"
      - "Instantor"
  import/extensions:
    - "error"
    - ignore:
      - "trustpilot"
      - "Instantor"
  max-len:
    - "error"
    - ignorePattern: "\\s*<"
      code: 100
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  react/jsx-filename-extension: "off"
  react/forbid-prop-types:
    - 2
    - forbid:
      - "any"
  no-underscore-dangle: "off"
  radix: "off"
  class-methods-use-this: "off"
  no-param-reassign: "off"
  no-unused-expressions:
    - "error"
    - allowTaggedTemplates: true
  react/self-closing-comp:
    - "error"
    - component: true
      html: false
  react/prefer-stateless-function: "off"
  jsx-a11y/no-static-element-interactions: "off"
  jsx-a11y/href-no-hash: "off"
  no-shadow: "off"
  react/jsx-no-target-blank: "off"
  import/no-extraneous-dependencies: "off"
  import/no-named-as-default: "off"
  jsx-a11y/click-events-have-key-events:
    - "warn"
  jsx-a11y/label-has-for:
    - "warn"
  jsx-a11y/anchor-is-valid:
    - "warn"
    - components:
      - "Link"
      specialLink:
      - "to"
      aspects:
      - "noHref"
      - "invalidHref"
      - "preferButton"
parser: "babel-eslint"
env:
  jest: true
